### ISSUE TITLE
despliegue plan_cuentas_crud 

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [davidmm07/plan_cuentas_crud#10]
desplegar en jenkins el API de presupuesto crud para que este disponible en el 254 en modo de desarrollo

**Comment by Soulfilip-UD** [comment]
Se registro en Jenkins, se creo el API en WSO2 y se registraron sus urls, también se asocio a un service provider. En espera por confirmar que las variables de entorno se encuentren en el servidor, y el funcionamiento con beego migrations sea exitoso, para el correcto desarrollo del API

**Comment by Soulfilip-UD** [comment]
Despliqgue exitoso, no se pública Url por mótivo de segridad.
Proceeding to close Issue :space_invader:
