### ISSUE TITLE
Generar Modelo de datos que soporte Asignar Rubro a Fuente de Financiamiento

### ISSUE THREAD

**Issue by davidmm07** [davidmm07/plan_cuentas_crud#14]
- [x] Definir modelo de datos entre la apropiacion del rubro y la fuente de financiamiento

**Comment by davidmm07** [comment]
Se añade gist primera revisión del modelo de fuentes: https://gist.github.com/davidmm07/77bce9e1b3b64e2a1de87b2fc1814623

**Comment by Soulfilip-UD** [comment]
Se complementa con el modelo de Datos en el Issue #15. Tarea finalizada . Proceeding to close Issue 👾
