### ISSUE TITLE
Modelo de Datos (FF): Crear, consultar -- Juan Camilo

### ISSUE THREAD

**Issue by juancsr** [davidmm07/plan_cuentas_crud#15]
Crear el modelo de datos para la consulta y creación de la fuente de financiamiento 
- [x] Modelo de datos creado
- [x] Script subido a la carpeta documentación drive
- [x] sql subido a la carpeta de documentación drive

**Comment by juancsr** [comment]
El modelo se puede encontrar aquí: https://drive.google.com/drive/u/2/folders/1qlCxYowQRYyBwzcxFtIWf5ftiUErYF51

**Comment by juancsr** [comment]
Modelo de datos fuente de financiamiento. 

![plan_cuentas_fuente_financiamiento](https://user-images.githubusercontent.com/19156525/59953479-e492f000-9445-11e9-8dc8-693e8e2f9b1a.png)

**Comment by juancsr** [comment]
[modelo_datos_ff.zip](https://github.com/udistrital/plan_cuentas_crud/files/3316159/modelo_datos_ff.zip)

**Comment by Soulfilip-UD** [comment]
Tarea completada en un 100%. Proceeding to close Issue 👾

**Comment by Soulfilip-UD** [comment]
Tener en cuenta el trabajo para el repositorio de documentación general
