### ISSUE TITLE
Modelo de datos para movimientos de fuentes de financiamiento

### ISSUE THREAD

**Issue by juancsr** [davidmm07/plan_cuentas_crud#16]
Crear un modelo de datos que soporte el registro de los movimientos relacionados a las fuentes de financiamiento
- [x] Modelo de datos
- [x] imagen del modelo subida a la documentación
- [x] Archivo .dbm subido a la documentación
- [x] sql subido a la documentación

**Comment by davidmm07** [comment]
Se agrega modelo generalizado de movimientos como propuesta aparte para generar un nuevo api de movimientos
![movimientosdbm](https://user-images.githubusercontent.com/15944053/59788345-1dd62f00-9291-11e9-9261-1eb06d1d1454.png)

**Comment by davidmm07** [comment]
Se agrega sql temporal del modelo de datos https://gist.github.com/davidmm07/7413717204f56241b4122a57b8db76da

**Comment by davidmm07** [comment]
Agregamos archivo .dbm temporal
https://gist.github.com/davidmm07/82ba1f521db09895f3fc4ef051ef6729

**Comment by Soulfilip-UD** [comment]
Tarea completada en un 100%. Proceeding to close Issue 👾

**Comment by Soulfilip-UD** [comment]
Tener en cuenta el trabajo realizado para con el repositorio de Documentación
