### ISSUE TITLE
Ajustar modelo de migración, subida y bajada con Beego migrations

### ISSUE THREAD

**Issue by davidmm07** [davidmm07/plan_cuentas_crud#19]
- [x] Ajustar modelo de  beego migrations en subida
- [x] Ajustar modelo de  beego migrations en bajada

**Comment by davidmm07** [comment]
Se ajuste modelo en subida para en el siguiente commit

**Comment by Soulfilip-UD** [comment]
Adjuntar PR correspondiente

**Comment by davidmm07** [comment]
Queda adjuntado pull request

**Comment by Soulfilip-UD** [comment]
Se realizo PR a la rama `master` ya que se deben evitar problemas en el despliegue con el comando `go get ...` 
Tarea finalizada
Proceeding to close Issue :space_invader:
