### ISSUE TITLE
Crear api crud para el negocio de plan de cuentas

### ISSUE THREAD

**Issue by davidmm07** [davidmm07/plan_cuentas_crud#2]
- [x] Generar api crud de plan de cuentas

**Comment by davidmm07** [comment]
Se agrega repositorio https://github.com/udistrital/plan_cuentas_crud y se genera proyecto api de beego.

**Comment by miguelramirez93** [comment]
Revisado y aprobado sin observaciones.

**Comment by miguelramirez93** [comment]
Se revisa la tarea. No se tiene observaciones
