### ISSUE TITLE
Incluir fuentes de Financiamiento en API de plan_cuentas_crud

### ISSUE THREAD

**Issue by mcguegi** [davidmm07/plan_cuentas_crud#20]
Se solicita realizar las siguientes tareas relacionadas con Fuentes de Financiamiento

- [x]  incluir operaciones CRUD de Fuentes de Financiamiento en API de plan_cuentas_crud

**Comment by mcguegi** [comment]
Se da por culminada tarea de agregar fuentes de financiamiento a CRUD. Se solicita a líder técnico @Soulfilip-UD la revisión de la misma

**Comment by Soulfilip-UD** [comment]
Adjuntar PR asociado ( El Issue en el comenario inicial del PR)

**Comment by mcguegi** [comment]
Se añade el issue en el PR asociado.

**Comment by Soulfilip-UD** [comment]
Tarea finalizada.
Proceeding to close Issue
