### ISSUE TITLE
Registro de fuentes de financiamiento plan_cuentas_crud 5 horas - Juan Camilo

### ISSUE THREAD

**Issue by juancsr** [davidmm07/plan_cuentas_crud#26]
Crear un servicio que cuando se registre una nueva fuente de financiamiento, se asocie también con la apropiación inicial de los rubros relacionados con la fuente, y las dependencias de dicha fuente, para que finalmente devuelva un arreglo con los id registrados en la tabla fuente_financiamiento_apropiacion.

- [x] Crear transacción para registro de fuente_financiamiento_apropiación
- [x] Crear servicio para utilizar la transacción

**Comment by juancsr** [comment]
Se crea un servicio que realiza una transacción para realizar **multiples registros de fuente_financiamiento_apropiacion**:

* **Tipo de petición**: POST
* **Parámetros**:
```json
[
   {
      "ApropiacionId":{
         "Id": 4
      },
      "FuenteFinanciamientoId":{
         "Id": 75
      },      
      "Dependencia": 2,
      "Valor": 150
   },
   {
      "ApropiacionId":{
         "Id": 4
      },
      "FuenteFinanciamientoId":{
         "Id": 75
      },
      "Dependencia": 3,
      "Valor": 200
   }
]
```
* **Endpoint**: fuente_financiamiento_apropiacion/registrar_multiple

* **URL**: http://localhost:8080/v1/fuente_financiamiento_apropiacion/registrar_multiple

![image](https://user-images.githubusercontent.com/19156525/60748166-b71f6980-9f50-11e9-8aa6-62cd5448770c.png)

**Comment by juancsr** [comment]
En el commit 
cefac09 
se crea tanto la transacción como el servicio que la utiliza

**Comment by Soulfilip-UD** [comment]
Gracias por la documentación.
Se revisaron los cambios y funciona correctamente

Tarea Finalizada
Proceeding to close Issue 👾
