### ISSUE TITLE
Carga Masiva del arbol de rubros , vigencia 2019 - Especificaciones de archivo a Francisco - 3 horas - Juan Camilo

### ISSUE THREAD

**Issue by juancsr** [davidmm07/plan_cuentas_crud#28]
Especificar que campos y que estructura debe tener el archivo para la migración del árbol de rubros desde sicapital

**Comment by juancsr** [comment]
[Listado_de_apropiaciones.pdf](https://github.com/udistrital/plan_cuentas_crud/files/3369637/Listado_de_apropiaciones.pdf)
Se envió un correo electrónico a @Soulfilip-UD proponiendo lo siguiente:
La estructura que debe tener el documento para solicitar de sicapital debe tener la siguiente información:
* Código del rubro
* Entidad del rubro
* Nombre del rubro
* Descripción del rubro
* Vigencia de la apropiación
* Valor de la apropiación

A demás, debe estar organizada y referenciada en forma de árbol, con la siguiente estructura: 

![image](https://user-images.githubusercontent.com/19156525/60831589-83765680-a17f-11e9-8b34-8dba04c99b6b.png)


La información debe tener el total de rubros como se muestra en el **reporte Listado de Apropiaciones** (se adjunta a este correo), en otras palabras, no solo las hojas, sino todos los rubros, en la medida de que sea posible, al menos sin la apropiación. 

Se recuerda que la información debe ser desde el 1 de enero de 2019 hasta el 30 de junio de 2019

**Comment by Soulfilip-UD** [comment]
Estructura realizada y remitida a Diana Ramirez para hacer la petición con Francisco del Arbol de Rubros

Proceeding to close Issue 👾
