### ISSUE TITLE
Dejar el response_format  all 100% en plan_cuentas_crud para pasar todas las pruebas - 8 horas - Miguel

### ISSUE THREAD

**Issue by miguelramirez93** [davidmm07/plan_cuentas_crud#31]
- [x] ajustar pruebas para response format

**Comment by miguelramirez93** [comment]
Se añaden todos los errores de autogenerados beego (https://github.com/udistrital/utils_oas/commit/08631136c6c857cbcd8c8cfb4d5899d0944fb3ce)

**Comment by Soulfilip-UD** [comment]
Tarea suspendida, el desarrollo sobre el repositorio se congelo al trabajar solamente con mongo

Se cierra el Issue
