### ISSUE TITLE
Definición Modelo de Datos Apropiaciones Iniciales

### ISSUE THREAD

**Issue by mcguegi** [davidmm07/plan_cuentas_crud#4]
Se debe generar el modelo de datos para el modulo de apropiaciones iniciales, lo cual comprende las siguientes subtareas:
- [x]  Creación del modelo en pgmodeler de acuerdo a los lineamientos
- [x]  Documentación de los objetos y campos de acuerdo al documento de análisis
- [x]  Generación del script para creación de la base de datos

**Comment by miguelramirez93** [comment]
Se revisa la tarea sin observaciones .

**Comment by Soulfilip-UD** [comment]
Se realiza la socialización de los modelos con Jhon Castellanos y los aprueba.
