### ISSUE TITLE
Desarrollo de procesos de apropiaciones en API (crud)

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [davidmm07/plan_cuentas_crud#7]
desarrollar los procesos de API crud en postgres necesarios para la gestión de apropiación inicial:
- [x] generar los modelos y controladores necesarios de acuerdo con el [modelo de BD](https://github.com/udistrital/plan_cuentas_crud/issues/4)
- [x] integración de los modelos y controladores de apropiaciones en plan de cuentas crud
- [x] pruebas iniciales de los endpoints con datos
- [x] Documentación del README.MD según los lineamientos

**Comment by CarlosGutierrezArdila** [comment]
commits:
5c92a18790c7543c8982936c7587607a6874abc2
0d8b6350e50c25b71eef3e9dcf5ecfcd603e368e
0e9f2169afba6671baa6f973e94b6f98e83ad571
581b92b4f3b0f3044684ee4302c4bb148f88539b
de28eedbecd7d7d9a7b2dfc3ce022d4b4158eb6e

**Comment by Soulfilip-UD** [comment]
Por favor asociar a un PR

**Comment by CarlosGutierrezArdila** [comment]
PR: https://github.com/udistrital/plan_cuentas_crud/pull/9

**Comment by Soulfilip-UD** [comment]
Tarea Finalizada, Se procede a cerrar el Issue
