### ISSUE TITLE
Generación del modelo de datos para árbol de rubros

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [davidmm07/plan_cuentas_crud#8]
Se debe generar el modelo de datos para el nuevo micro servicio de árbol de rubros, lo cual comprende las siguientes subtareas:
- [x]  Creación del modelo en pgmodeler de acuerdo a los lineamientos
- [x]  Documentación de los objetos y campos de acuerdo al [documento](https://docs.google.com/document/d/1DHKWStkSUNSBZbmq6lSGKDDfh--YWSs708mqMDnPyO4/edit) de análisis
- [x]  Generación del script para creación de la base de datos

**Comment by Soulfilip-UD** [comment]
Se realiza la socialización de los modelos con Jhon Castellanos y los aprueba.
